# MetaCLIP ViT-L/14
vision_encoder:
  id: clip_meta__l14
  display_name: "CLIP Meta L/14"
  type: open_clip_hub
  model_name: ViT-L-14
  pretrained: metaclip
  weights_path: /cache/ckpt/download/tokenizer/continuous/vit_l14_metaclip.safetensors
  processor_path: /cache/ckpt/download/tokenizer/continuous/clip-vit-large-patch14
  force_quick_gelu: true
  select_layer: -2
