# webssl dino3b full2b 224 (HuggingFace transformers)
vision_encoder:
  id: webssl_dino3b_full2b_224
  display_name: "webssl dino3b full2b 224"
  type: hf
  model_name_or_path: /cache/ckpt/download/tokenizer/continuous/webssl/webssl-dino3b-full2b-224
  select_layer: -1
  select_feature: patch
  image_size: 224
