# Qwen3-1.7B + Pixio ViT-B/16 @256
experiment:
  description: "Qwen3-1.7B + Pixio ViT-B/16 @256 + mlp2x"

llm: qwen3_1p7b
vision_encoder: pixio_vitb16
projector: mlp2x

eval:
  conv_mode: qwen_3

train:
  pretrain:
    learning_rate: 1.0e-3
    warmup_ratio: 0.05
    max_grad_norm: 1.0
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: '{"use_reentrant": false}'
    tf32: true
    dataloader_drop_last: true
  finetune:
    max_grad_norm: 1.0
    gradient_checkpointing_kwargs: '{"use_reentrant": false}'
    dataloader_drop_last: true
