# dinov2 base (HuggingFace transformers)
vision_encoder:
  id: dinov2_base
  display_name: "dinov2 base"
  type: hf
  model_name_or_path: /cache/ckpt/download/tokenizer/continuous/dinov2/dinov2-base
  select_layer: -1
  select_feature: patch
  image_size: 518
