# Perception Encoder PE-Core-L14-336
vision_encoder:
  id: pe_core_l14_336
  display_name: "PE-Core-L14-336"
  type: pe
  model_name: PE-Core-L14-336
  pe_config: PE-Core-L14-336
  weights_path: /cache/ckpt/download/tokenizer/continuous/pe/PE-Core-L14-336/PE-Core-L14-336.pt
  image_size: 336
  select_layer: -1
  select_feature: patch
  pe_repo: /home/ma-user/work_space/VTB/third_party/perception_models
