# Perception Encoder PE-Core-S16-384
vision_encoder:
  id: pe_core_s16_384
  display_name: "PE-Core-S16-384"
  type: pe
  model_name: PE-Core-S16-384
  pe_config: PE-Core-S16-384
  weights_path: /cache/ckpt/download/tokenizer/continuous/pe/PE-Core-S16-384/PE-Core-S16-384.pt
  image_size: 384
  select_layer: -1
  select_feature: patch
  pe_repo: /home/ma-user/work_space/VTB/third_party/perception_models
