# Perception Encoder PE-Spatial-B16-512
vision_encoder:
  id: pe_spatial_b16_512
  display_name: "PE-Spatial-B16-512"
  type: pe
  model_name: PE-Spatial-B16-512
  pe_config: PE-Spatial-B16-512
  weights_path: /cache/ckpt/download/tokenizer/continuous/pe/PE-Spatial-B16-512/PE-Spatial-B16-512.pt
  image_size: 512
  select_layer: -1
  select_feature: patch
  pe_repo: /home/ma-user/work_space/VTB/third_party/perception_models
