# DINOv3 ViT-S+/16 @256
vision_encoder:
  id: dinov3_vits16plus
  display_name: "DINOv3 ViT-S+/16 @256"
  type: dinov3
  weights_path: /cache/ckpt/download/tokenizer/continuous/dinov3/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
  image_size: 256
  select_layer: -1
  select_feature: patch
  dinov3_backbone: dinov3_vits16plus
  dinov3_repo: /home/ma-user/work_space/VTB/third_party/dinov3
