# DINOv3 ConvNeXt-L @256
vision_encoder:
  id: dinov3_convnext_large
  display_name: "DINOv3 ConvNeXt-L @256"
  type: dinov3
  weights_path: /cache/ckpt/download/tokenizer/continuous/dinov3/dinov3_convnext_large_pretrain_lvd1689m-61fa432d.pth
  image_size: 256
  select_layer: -1
  select_feature: patch
  dinov3_backbone: dinov3_convnext_large
  dinov3_repo: /home/ma-user/work_space/VTB/third_party/dinov3
