# DINOv3 ConvNeXt-S @256
vision_encoder:
  id: dinov3_convnext_small
  display_name: "DINOv3 ConvNeXt-S @256"
  type: dinov3
  weights_path: /cache/ckpt/download/tokenizer/continuous/dinov3/dinov3_convnext_small_pretrain_lvd1689m-296db49d.pth
  image_size: 256
  select_layer: -1
  select_feature: patch
  dinov3_backbone: dinov3_convnext_small
  dinov3_repo: /home/ma-user/work_space/VTB/third_party/dinov3
