# EUPE-ConvNeXt-S
vision_encoder:
  id: eupe_convnext_s
  display_name: "EUPE-ConvNeXt-S"
  type: eupe
  model_name: EUPE-ConvNeXt-S
  eupe_hub: eupe_convnext_small
  weights_path: /cache/ckpt/download/tokenizer/continuous/eupe/EUPE-ConvNeXt-S/EUPE-ConvNeXt-S.pt
  image_size: 256
  select_layer: -1
  select_feature: patch
  eupe_repo: /home/ma-user/work_space/VTB/third_party/eupe
