# dino vitb16 (HuggingFace transformers)
vision_encoder:
  id: dino_vitb16
  display_name: "dino vitb16"
  type: hf
  model_name_or_path: /cache/ckpt/download/tokenizer/continuous/dino/dino-vitb16
  select_layer: -1
  select_feature: patch
  image_size: 224
