# dino vits8 (HuggingFace transformers)
vision_encoder:
  id: dino_vits8
  display_name: "dino vits8"
  type: hf
  model_name_or_path: /cache/ckpt/download/tokenizer/continuous/dino/dino-vits8
  select_layer: -1
  select_feature: patch
  image_size: 224
